name: Build Test Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Repo checkout  
      uses: actions/checkout@v6

    - name: Use Node.js 24
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'npm'

    - name: Clean install project dependencies    
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    # - name: Run Playwright tests
    #   run: npx playwright test

    - name: Build UI
      run: npm run start &
    
    - name: Run Playwright tests  
      run: npm test
